feat(pipelines): support directional connectors
patternfly/react-topology pull request #163
Opened 2024-03-14 14:52 UTC by jenny-s51

## What
Closes #156 

- [x] Feature
- [ ] Bugfix
- [ ] Code style update (formatting, renaming)
- [ ] Refactoring (no functional changes, no api changes)
- [ ] Build related changes
- [ ] Documentation content changes
- [ ] Other (please describe):

## Screen shots / Gifs for design review

2024-03-15 14:08 UTC, jeff-phillips-18 requested changes

2024-03-15 14:08 UTC, jeff-phillips-18 commented on packages/module/src/pipelines/utils/utils.ts
> +  finallyEdgeType = DEFAULT_FINALLY_EDGE_TYPE
we can't change the default setting. Applications won't necessarily have the new edge type in their component factory and this would break them.

2024-03-18 19:25 UTC, jenny-s51 commented on packages/demo-app-ts/src/demos/pipelinesDemo/PipelineOptionsBar.tsx
> +          label="Terminal type"
👍 , updated

2024-03-19 17:52 UTC, jeff-phillips-18 commented on packages/module/src/components/edges/terminals/DefaultConnectorTerminal.tsx
> +  endPoint?: Point;
These are not used.

2024-03-20 14:44 UTC, jeff-phillips-18 approved these changes

2024-03-20 18:57 UTC, jessiehuff approved these changes

2024-03-20 18:57 UTC, merged